### ISSUE TITLE
Redmine 4 - NameError (uninitialized constant MyPagePatches::WelcomeControllerPatch::InstanceMethods::MypageHelper

### ISSUE THREAD

**Issue by vsc55** [gtt-project/redmine_my_page#2]
If option "Override home link to users landing page" is true and you click link Home show error internal.

In log show error:
```
Started GET "/" for 127.0.0.1 at 2019-01-25 13:57:59 +0100
Processing by WelcomeController#index as HTML
  Current user: XXX (id=X)
Completed 500 Internal Server Error in 23ms (ActiveRecord: 10.7ms)
  
NameError (uninitialized constant MyPagePatches::WelcomeControllerPatch::InstanceMethods::MypageHelper
Did you mean?  MyPagePatches):
  
plugins/redmine_my_page/lib/my_page_patches/welcome_controller_patch.rb:17:in `landing_page_index'
lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by eyewritecode** [comment]
@vsc55 I can't reproduce that error. Which version of Redmine are you using? Also which branch of this repository did you use?

**Comment by vsc55** [comment]
Hi,
This is the information of the version I use:
![info](https://user-images.githubusercontent.com/13438676/52162790-4b06b400-26d9-11e9-9548-726e2cc1690c.png)
![image](https://user-images.githubusercontent.com/13438676/52162811-843f2400-26d9-11e9-9c3d-1e31d74a7b39.png)

**Comment by sanak** [comment]
@vsc55 Could you try our latest `develop` branch, again ?
Thanks,

**Comment by vsc55** [comment]
Ok, solved. 👍 
Now it works correctly,
Thanks.
