### ISSUE TITLE
Add Japanese locale

### ISSUE THREAD

**Issue by sanak** [gtt-project/redmine_my_page#9]
**Problem**
Currently, Japanese locale is missing.

**Improvement**
Add Japanese locale.

**Comment by dkastl** [comment]
Also good to provide localization strings for generated labels such as labels in permissions for example. It just looks better, also in English. Example:

```
  project_module_<plugin_name>: "<...>"
  permission_view_<plugin_name>: "View <...>"
```

**Comment by sanak** [comment]
Okay, thanks for the information.
About my page plugin, there seems to be no place which above translation appears, so I will keep current `en.yml` words as it is.
